config/routes.rb
Rails.application.routes.draw do
  resources :properties do
    collection do
      get 'search' 
    end
  end


  devise_for :account
  root to: 'properties#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable , :trackable , :confirmable

  has_many :properties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
class Property < ApplicationRecord
    has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:update,keys: [:first_name, :last_name, :url]) 
        devise_parameter_sanitizer.permit(:sign_up,keys: [:first_name, :last_name]) 
        # do |user_params|
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy!

    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :address, :price, :rooms, :bathrooms, :photo)
    end

    def search
      @properties = Property.where("address ILIKE ?", "%#{params[:address]}%")
      logger.debug "@properties: #{@properties}"
      render :index
    rescue NoMethodError
      @properties = []
      render :index
    end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def main
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/layouts/_footer.html.erb
<footer class="container  text-center my-4">
    <p>&copy; Property Finder 2023 </p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PropertyFinder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>

  <body>
  <header>
    <%= render "layouts/nav/public" %>
  </header>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
  
    <%= render "layouts/footer" %>
    
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

  </body>
</html>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top ">
  <div class="container-fluid">
    <h4><a class="navbar-brand" href="#"> PROPERTY FINDER </a></h4>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#" > News </a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="#" > Advertising </a>
      </li>
   </ul>
   <ul class="navbar-nav">
      <% if account_signed_in? %>
      <li class="nav-item">
      <%= link_to "Log Out", destroy_account_session_path, method: :delete, class:"nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
     <%= link_to "Log In", new_account_session_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
    <%= link_to "Sign Up", new_account_registration_path, class:"nav-link" %>
   </li>
   <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/properties/_form.html.erb
<%= form_with(model: property,local: true, html: { class: 'property-form' }) do |form| %>
  <% if property.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name,class: 'form-control' %>
  </div>

  <div class="form-group" >
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address,class: 'form-control' %>
  </div>

  <div class="form-group" >
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price,class: 'form-control' %>
  </div>

  <div class="form-group" >
    <%= form.label :rooms, style: "display: block" %>
    <%= form.number_field :rooms,class: 'form-control' %>
  </div>

  <div class="form-group" >
    <%= form.label :bathrooms, style: "display: block" %>
    <%= form.number_field :bathrooms,class: 'form-control' %>
  </div>

  <div class="form-group" >
    <%= form.label :photo, style: "display: block" %>
    <%= form.file_field :photo,class: 'form-control' %>
  </div>

  <div class="actions" >
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/_property.html.erb
<div class="single-property" id="<%= dom_id property %>">
  <h1 class="m-3" >
    <%= property.name %>
  </h1>

  <p class="property-photo" >
    <% if property.photo.attached? %>
    <%= image_tag property.photo %>
  <% else %>
    No photo available
  <% end %>
</p>

  <p>
    <strong>Address:</strong>
    <%= property.address %>
  </p>

  <p>
    <strong>Price:</strong> $
    <%= property.price %>
  </p>

  <p>
    <strong>Rooms:</strong>
    <%= property.rooms %>
  </p>

  <p>
    <strong>Bathrooms:</strong>
    <%= property.bathrooms %>
  </p>

</div>

app/views/properties/edit.html.erb
<h1 class="text-center" >Editing property</h1>
<%= render "form", property: @property %>

<br>

<div class="text-center" >
  <%= link_to "Show this property", @property %> |
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="search">
  <h1 class="display-3 text-center "> Search for your new home today... </h1>
  <div class="row">
  <div class="col-3"></div>
    <div class="col-6">
      <%= form_with(url: search_properties_path, method: "get") do %>
        <div class="input-group">
          <%= text_field_tag :address, params[:address], class: "form-control", placeholder: "Search by Address" %>
          <%= submit_tag "Search", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
    <div class="col-3"></div>
  </div>
</div>
        
<h1 class="text-center my-4" >Properties</h1>
<a href="<%= new_property_path %>" class="btn btn-primary">Add Property</a>


<div class="row" id="properties">
  <% @properties.each do |property| %>
    <div class="col-lg-4 my-3" id="home-property" >
   <h3 class="text-center " > <%= property.name %></h3>
   <% if property.photo.attached? %>
   <%= image_tag property.photo, class: "img-fluid" %>
 <% else %>
   <p>No photo available</p>
 <% end %>
 <h5> <%= property.address %></h5>
    <p class="text-center" >
      <%= link_to "Show this property", property , class:"show-more-link" %>
    </p>
    </div>
  <% end %>
</div>

app/views/properties/new.html.erb
<h1 class="text-center my-3" >New property</h1>
<%= render "form", property: @property %>

<br>

<div class="text-center" >
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @property %>

<div class="single-property-link" >
  <%= link_to "Edit this property", edit_property_path(@property) %> |
  <%= link_to "Back to properties", properties_path %>
 <h6>
  <%= button_to "Destroy this property !!!", @property, method: :delete %>
  </h6>
</div>